### PR TITLE
fix delete device flyout description

### LINKED ISSUE #719: Text on Delete Device Dialog is duplicated
# Type of issue 

- [ x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Make sure text on the delete dialog matches the design when a simulated and physical device are both selected.  Right now two strings are duplicated:
'''	Deleting simulated devices is not currently supported, this action will only be taken on the physical devices.'''
below it:
'''	Deleting simulated devices is not currently supported, this action will only be taken on the physical devices.'''

### PR DESCRIPTION
**Pull request by maple10001**
# Type of change? 

- [x] Bug fix
- [ ] New feature
- [ ] Enhancement
- [ ] Breaking change (breaks backward compatibility)

# Description, Context, Motivation 
fix #719 

...

**Checklist:**

- [ ] All tests passed
- [ ] The code follows the code style and conventions of this project
- [ ] The change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

File: src/components/flyout/deviceDeletionFlyout.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ class DeviceDeletionFlyout extends React.Component {
             {lang.DELETE_DEVICE}
           </div>
           <div className="content-description">
-            {IsSimulated ? lang.NOT_ABLE_TO_DELETE : lang.DELETE_DEVICE_DESCRIPTION}
+            {lang.DELETE_DEVICE_DESCRIPTION}
```
Comment (spryor) [inline src/components/flyout/deviceDeletionFlyout.js]: There should always be text on the delete page. The notification box should only appear when simulated devices are being ignored. See the design from https://github.com/Azure/pcs-remote-monitoring-webui/issues/584
