### PR TITLE
fix update alarm status on maintanence page

### LINKED ISSUE #608: Alarms: Ack, Open, Close buttons don’t work
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
Ack, Open, Close buttons don’t work for alarms.

### PR DESCRIPTION
**Pull request by maple10001**
# Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] The code follows the code style and conventions of this project.
- [ ] The change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

# Description of the change

- update alarm status in redux store rather than component state

# Motivation for the change

- fix #608

### CODE REVIEW

File: src/components/pages/maintenance/maintenance.js [hunk 1]
```diff
@@ -120,7 +119,14 @@ class MaintenancePage extends Component {
     const { selectedAlarms } = this.state;
     Promise.all(
       selectedAlarms.map(alarm => ApiService.updateAlarmsStatus({...alarm, Status}))
-    ).then(updatedAlarms => this.setState({ updatedAlarms }));
+    ).then(updatedAlarms => {
+      if (updatedAlarms && updatedAlarms.length > 0) {console.log(updatedAlarms)
```
Comment (spryor) [inline src/components/pages/maintenance/maintenance.js]: This console log should be removed.
